import { PrismaClient } from "@prisma/client"
import chalk from "chalk"

const prisma = new PrismaClient()

const horoscopeData = [
  {
    sign: "Aries",
    element: "Fire",
    rulingPlanet: "Mars - The Warrior",
    traits: ["Courageous", "Passionate", "Energetic", "Independent", "Bold"],
    strength: "Your fierce determination cuts through obstacles. You initiate and inspire action.",
    challenge: "Channel your intensity with awareness. Impulsiveness can create unnecessary conflicts.",
    compatibleSigns: ["Leo", "Sagittarius", "Gemini", "Aquarius"],
    todayTheme: "Channel your fierce energy into focused action. This is your day to lead.",
    advice: "Your boldness is your strength—use it wisely. Pause before reacting to conserve energy.",
    luckyNumber: 7,
    bestTime: "Early morning (5-7 AM)",
    lifeLesson: "Learning to balance courage with compassion, action with reflection.",
    shadowAspect: "Unbridled aggression, recklessness, dominance without empathy.",
    spiritualGift: "You bring initiation and courage to the world. You're the spark that ignites change.",
  },
  {
    sign: "Taurus",
    element: "Earth",
    rulingPlanet: "Venus - The Lover",
    traits: ["Stable", "Sensual", "Reliable", "Grounded", "Patient"],
    strength: "Your steadiness creates security. You build lasting foundations in all you do.",
    challenge: "Resist rigidity. Embrace change while honoring your need for stability.",
    compatibleSigns: ["Virgo", "Capricorn", "Cancer", "Pisces"],
    todayTheme: "Slow and steady. Trust your senses and groundedness today.",
    advice: "Your strength lies in steadiness. Take time to nurture yourself and others.",
    luckyNumber: 6,
    bestTime: "Late morning (10 AM-12 PM)",
    lifeLesson: "Understanding that true security comes from within, not from external possessions.",
    shadowAspect: "Stubbornness, materialism, possessiveness, resistance to transformation.",
    spiritualGift: "You embody stability and sensory presence. You teach us to appreciate the physical world.",
  },
  {
    sign: "Gemini",
    element: "Air",
    rulingPlanet: "Mercury - The Messenger",
    traits: ["Curious", "Communicative", "Versatile", "Playful", "Intellectual"],
    strength: "Your curiosity opens doors. You connect people, ideas, and possibilities.",
    challenge: "Go deeper. Seek substance beyond surface-level knowledge and connections.",
    compatibleSigns: ["Libra", "Aquarius", "Aries", "Leo"],
    todayTheme: "Your words hold power. Share your thoughts and connect with others.",
    advice: "Listen as much as you speak. Your curious mind is your gift—use it to understand.",
    luckyNumber: 5,
    bestTime: "Midday (12-2 PM)",
    lifeLesson: "Discovering that wisdom comes from depth, not just breadth of knowledge.",
    shadowAspect: "Superficiality, gossip, scattered energy, inability to commit.",
    spiritualGift: "You are the communicator and bridge-builder. You bring information and connection.",
  },
  {
    sign: "Cancer",
    element: "Water",
    rulingPlanet: "Moon - The Nurturer",
    traits: ["Intuitive", "Protective", "Emotional", "Nurturing", "Empathetic"],
    strength: "Your emotional depth is your superpower. You feel what others hide.",
    challenge: "Honor your feelings without being consumed by them. Set emotional boundaries.",
    compatibleSigns: ["Scorpio", "Pisces", "Taurus", "Virgo"],
    todayTheme: "Trust your intuition. Your emotional depth is your superpower.",
    advice: "Nurture yourself as you nurture others. Your sensitivity is your strength.",
    luckyNumber: 2,
    bestTime: "Evening (6-8 PM)",
    lifeLesson: "Learning that vulnerability is strength, and emotional honesty heals.",
    shadowAspect: "Emotional manipulation, neediness, resentment from unmet expectations.",
    spiritualGift: "You are the healer and protector. You teach us to honor emotions and belonging.",
  },
  {
    sign: "Leo",
    element: "Fire",
    rulingPlanet: "Sun - The Creator",
    traits: ["Confident", "Generous", "Creative", "Natural Leader", "Expressive"],
    strength: "Your light illuminates the world. You inspire through authentic expression.",
    challenge: "Lead with generosity, not ego. Remember that all stars shine equally.",
    compatibleSigns: ["Aries", "Sagittarius", "Gemini", "Libra"],
    todayTheme: "Shine brightly. Your light is meant to illuminate the world.",
    advice: "Your courage inspires others—use it to lift them up, not dominate.",
    luckyNumber: 1,
    bestTime: "Midday (1-3 PM)",
    lifeLesson: "Understanding that true greatness comes from lifting others, not being above them.",
    shadowAspect: "Narcissism, arrogance, need for constant validation and admiration.",
    spiritualGift: "You are the creator and celebrator. You teach us to shine authentically.",
  },
  {
    sign: "Virgo",
    element: "Earth",
    rulingPlanet: "Mercury - The Analyst",
    traits: ["Analytical", "Practical", "Detail-oriented", "Helpful", "Modest"],
    strength: "Your precision creates harmony. You see what others miss and fix it.",
    challenge: "Release perfectionism. Progress matters more than perfection.",
    compatibleSigns: ["Taurus", "Capricorn", "Cancer", "Scorpio"],
    todayTheme: "Perfect your craft. Your attention to detail creates harmony.",
    advice: "Your critical eye is valuable—turn it toward progress, not perfection.",
    luckyNumber: 3,
    bestTime: "Morning (7-9 AM)",
    lifeLesson: "Accepting that imperfection is human, and good enough is often perfect.",
    shadowAspect: "Perfectionism, harsh criticism, anxiety, servitude without boundaries.",
    spiritualGift: "You are the healer and helper. You teach us that service creates meaning.",
  },
  {
    sign: "Libra",
    element: "Air",
    rulingPlanet: "Venus - The Harmonizer",
    traits: ["Balanced", "Diplomatic", "Artistic", "Social", "Indecisive"],
    strength: "Your balance creates harmony. You see all perspectives and bridge divides.",
    challenge: "Make decisions for yourself. Your needs matter as much as others'.",
    compatibleSigns: ["Gemini", "Aquarius", "Leo", "Sagittarius"],
    todayTheme: "Seek balance in all things. Your presence brings harmony.",
    advice: "Trust your judgment. Harmony doesn't require always pleasing everyone.",
    luckyNumber: 6,
    bestTime: "Afternoon (2-4 PM)",
    lifeLesson: "Learning that true balance includes honoring your own needs and boundaries.",
    shadowAspect: "Indecision, people-pleasing, lack of authenticity, superficial relationships.",
    spiritualGift: "You are the peacemaker and artist. You teach us about beauty and balance.",
  },
  {
    sign: "Scorpio",
    element: "Water",
    rulingPlanet: "Pluto - The Transformer",
    traits: ["Intense", "Secretive", "Powerful", "Magnetic", "Transformative"],
    strength: "Your intensity reveals hidden truths. You transform through depth.",
    challenge: "Trust others with your depth. Secrecy often comes from old wounds.",
    compatibleSigns: ["Cancer", "Pisces", "Virgo", "Capricorn"],
    todayTheme: "Dive deep. Your intensity reveals hidden truths.",
    advice: "Release what no longer serves you. Your power is in transformation.",
    luckyNumber: 8,
    bestTime: "Night (8-10 PM)",
    lifeLesson: "Understanding that vulnerability with the right people creates true intimacy.",
    shadowAspect: "Obsession, vengeful resentment, manipulation, emotional toxicity.",
    spiritualGift: "You are the transformer and alchemist. You teach us about rebirth and depth.",
  },
  {
    sign: "Sagittarius",
    element: "Fire",
    rulingPlanet: "Jupiter - The Expander",
    traits: ["Adventurous", "Optimistic", "Philosophical", "Free-spirited", "Honest"],
    strength: "Your optimism expands possibilities. You inspire through truth.",
    challenge: "Ground your dreams in reality. Freedom requires responsibility.",
    compatibleSigns: ["Aries", "Leo", "Libra", "Aquarius"],
    todayTheme: "Expand your horizons. Adventure awaits.",
    advice: "Share your optimism. But ground your dreams in reality too.",
    luckyNumber: 9,
    bestTime: "Late afternoon (4-6 PM)",
    lifeLesson: "Discovering that true freedom comes from responsibility, not escape.",
    shadowAspect: "Recklessness, irresponsibility, blunt insensitivity, escapism.",
    spiritualGift: "You are the adventurer and teacher. You inspire us to seek meaning.",
  },
  {
    sign: "Capricorn",
    element: "Earth",
    rulingPlanet: "Saturn - The Builder",
    traits: ["Disciplined", "Ambitious", "Practical", "Responsible", "Stoic"],
    strength: "Your discipline builds empires. You create lasting structures.",
    challenge: "Balance ambition with joy. Success without fulfillment is hollow.",
    compatibleSigns: ["Taurus", "Virgo", "Scorpio", "Pisces"],
    todayTheme: "Build with intention. Your patience creates lasting structures.",
    advice: "Trust the climb. Your hard work lays a strong foundation.",
    luckyNumber: 10,
    bestTime: "Early morning (6-8 AM)",
    lifeLesson: "Learning that authority and mastery come from integrity, not control.",
    shadowAspect: "Rigidity, coldness, workaholism, emotional detachment, cynicism.",
    spiritualGift: "You are the builder and wise elder. You teach us about responsibility.",
  },
  {
    sign: "Aquarius",
    element: "Air",
    rulingPlanet: "Uranus - The Rebel",
    traits: ["Innovative", "Independent", "Eccentric", "Humanitarian", "Detached"],
    strength: "Your uniqueness changes the world. You see what's possible.",
    challenge: "Connect emotionally. Revolution needs heart, not just intellect.",
    compatibleSigns: ["Gemini", "Libra", "Aries", "Sagittarius"],
    todayTheme: "Think differently. Your unique perspective changes the world.",
    advice: "Honor your individuality. The world needs your unconventional wisdom.",
    luckyNumber: 11,
    bestTime: "Late night (10 PM-12 AM)",
    lifeLesson: "Understanding that true innovation requires both vision and human connection.",
    shadowAspect: "Detachment, coldness, rebellion without purpose, social alienation.",
    spiritualGift: "You are the revolutionary and visionary. You inspire us toward evolution.",
  },
  {
    sign: "Pisces",
    element: "Water",
    rulingPlanet: "Neptune - The Dreamer",
    traits: ["Imaginative", "Compassionate", "Spiritual", "Empathetic", "Intuitive"],
    strength: "Your imagination connects realms. You heal through empathy.",
    challenge: "Ground your dreams. Boundaries protect your sensitivity.",
    compatibleSigns: ["Cancer", "Scorpio", "Taurus", "Capricorn"],
    todayTheme: "Dream vividly. Your imagination connects realms beyond the physical.",
    advice: "Ground your dreams in reality. Protect your compassionate heart.",
    luckyNumber: 12,
    bestTime: "Evening (7-9 PM)",
    lifeLesson: "Discovering that compassion with boundaries is true wisdom.",
    shadowAspect: "Escapism, victim mentality, boundary-lessness, delusion.",
    spiritualGift: "You are the dreamer and healer. You teach us about magic and compassion.",
  },
]

async function main() {
  console.log(chalk.blue("🌙 Seeding horoscope data...\n"))

  for (const data of horoscopeData) {
    await prisma.horoscope.upsert({
      where: { sign: data.sign },
      update: {},
      create: data,
    })
  }

  console.log(chalk.green(`✅ Seeded ${horoscopeData.length} horoscope entries!`))
  console.log(chalk.yellow("\n🌟 Horoscope database is ready.\n"))
}

main()
  .catch((e) => {
    console.error(chalk.red("❌ Seeding failed:"), e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
